[2023-07-03 06:34:31,466][classifier.eval][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 06:34:31,571][classifier.eval][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 06:34:31,600][classifier.eval][INFO] - Instantiating loggers...
[2023-07-03 06:34:31,600][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/eval.py", line 35, in evaluate
    logger: List[LightningLoggerBase] = utils.instantiate_loggers(cfg.get("logger"))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'classifier.utils.utils' has no attribute 'instantiate_loggers'
[2023-07-03 06:34:31,602][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/outputs/2023-07-03/06-34-31
