[2023-07-21 20:00:16,674][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-21 20:00:16,770][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-21 20:00:16,802][classifier.train][INFO] - Instantiating loggers...
[2023-07-21 20:00:16,802][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 48, in train
    logger: List[Logger] = utils.instantiate_loggers(cfg.get("logger"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'classifier.utils.utils' has no attribute 'instantiate_loggers'
[2023-07-21 20:00:16,805][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/outputs/2023-07-21/20-00-16
