[2023-07-03 06:37:54,556][classifier.eval][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 06:37:54,667][classifier.eval][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 06:37:54,701][classifier.eval][INFO] - Instantiating loggers...
[2023-07-03 06:37:54,701][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/eval.py", line 35, in evaluate
    logger: List[LightningLoggerBase] = utils.instantiators.instantiate_loggers(cfg.get("logger"))
                                        ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'classifier.utils.utils' has no attribute 'instantiators'
[2023-07-03 06:37:54,703][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/outputs/2023-07-03/06-37-54
